<a href="https://colab.research.google.com/github/samhithaPeddireddy/Samhitha_Info5502_Spring2022/blob/Python-and-Machine-Learning/5412_HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 1: Combining tensors, Linear Algebra, and simple Neural Nets


---


#### **<font color="dodgerblue">Due date: Tuesday, 27. Sep, 12:00 PM</font>**

Each problem set below is marked with one or more $\star$'s to indicate difficulty. 

## Basic work with tensors ($\star$)


---

Write small programs using `torch` to answer the following questions. 

1. Define a zeroth-order tensor `t0` with whatever value(s) you like.

In [1]:
!pip3 install torch==1.2.0+cu92 torchvision==0.4.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 663.1 MB 1.7 kB/s 
     |████████████████████████████████| 8.8 MB 42.4 MB/s 
  Attempting uninstall: torch
    Found existing installation: torch 1.12.1+cu113
    Uninstalling torch-1.12.1+cu113:
      Successfully uninstalled torch-1.12.1+cu113
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.13.1+cu113
    Uninstalling torchvision-0.13.1+cu113:
      Successfully uninstalled torchvision-0.13.1+cu113
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchtext 0.13.1 requires torch==1.12.1, but you have torch 1.2.0+cu92 which is incompatible.
torchaudio 0.12.1+cu113 requires torch==1.12.1, but you have torch 1.2.0+cu92 which 

In [1]:
import torch

In [93]:
t0=torch.tensor(8)
print(t0)

tensor(8)


2. Define a first-order tensor `t1` with 6 randomly sampled (Gaussian) values.

   Multiply `t1` by `t0`.

   What is the sum of the elements in `t1`?

In [94]:

# create the mean with 6 values
mean = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0,6.0])

# create the standard deviation with 6 values
std = torch.tensor([1.22, 0.78, 0.56, 1.23, 0.23,0.9])
t1= torch.normal(mean, std)
print(t1)
t1=t1*t0
print(t1)
# create normal distribution

t1.sum()

tensor([-0.0245,  2.1313,  3.9463,  3.4312,  5.0105,  6.3792])
tensor([-0.1957, 17.0500, 31.5701, 27.4495, 40.0842, 51.0337])


tensor(166.9919)

3. Define a second-order tensor `t2` with 2 rows by transforming `t1` directly. 

   Now define a 2 X 2 X 3 third-order tensor `t3` by hand. Choose any numbers you like. 

In [95]:
t2=t1.reshape(2,3)
print(t2)
t3=torch.tensor([[[1,2,3],[2,3,4]],[[4,5,6],[5,3,2]]])
print(t3)

tensor([[-0.1957, 17.0500, 31.5701],
        [27.4495, 40.0842, 51.0337]])
tensor([[[1, 2, 3],
         [2, 3, 4]],

        [[4, 5, 6],
         [5, 3, 2]]])


4. Define another first order tensor `t1a` with 6 randomly sampled (Gaussian) values. 

  Multiply `t1a` and `t1` element-wise (Hadamard product). 

In [96]:
tla=torch.normal(mean=torch.arange(1., 7.), std=torch.arange(1, 0, -0.18))
print(tla)
print(t1*tla)

tensor([0.1964, 1.2903, 3.1133, 4.3506, 4.8795, 5.8883])
tensor([-3.8429e-02,  2.1999e+01,  9.8288e+01,  1.1942e+02,  1.9559e+02,
         3.0050e+02])


5. Define another first-order tensor `t1b` by taking every third value of `t1`.

  Multiply `t2` by `t1b`.

In [97]:
tlb=t1[2::3]
print(tlb)
t2=t2.reshape(3,2)
t2
torch.mv(t2,tlb)

tensor([31.5701, 51.0337])


tensor([ 863.9487, 2397.5242, 3869.9038])

6. Multiply `t2` by itself element-wise.

   Now multiply `t2` by itself using Matrix-Matrix multiplication.

In [98]:
t2=t2.reshape(2,3)
t2=t2*t2
print(t2)
torch.mm(t2,t2.reshape(3,2))

tensor([[3.8294e-02, 2.9070e+02, 9.9667e+02],
        [7.5348e+02, 1.6067e+03, 2.6044e+03]])


tensor([[1891135.6250, 2814825.7500],
        [5786094.5000, 8212786.5000]])

## Solve the following problems ($\star$)


---

Write your answers using nice-looking $\LaTeX$ vectors and matrices in the text box below each equation (see the accompanying tutorial if you are unfamiliar with $\LaTeX$).

**Avoid using `torch` if you can!** Simple Python mathematical operators should be enough.

7. 
<br><br> 
$ \begin{bmatrix} 6 \\ 2 \\ 5\end{bmatrix} \odot \begin{bmatrix} 1 \\ 0 \\ 0.3 \end{bmatrix} = $ 


**Your answer:**
<br><br> 
$ \begin{bmatrix} 6 \\ 0 \\ 1.5\end{bmatrix}
$

8. 
<br><br> 
$ \begin{bmatrix} 10 & 0.05 & -4 \\ 2 & 2 & 9 \end{bmatrix} \cdot \begin{bmatrix} -0.1 \\ 5 \\ 1 \end{bmatrix} = $


**Your answer:**
$ \begin{bmatrix} -4.75\\ 18.8 \end{bmatrix}
$

## Which of the Linear Algebra functions are encoded by these neural nets? ($\star\star$)


---



**For each of the neural nets, enter the following information in the text box below:**
- a plain-language description of the process that leads from the input to the output
  - e.g., *An X is multiplied by a Y to produce a Z*   
- the proper name for the relationship (where available), or a simple formula (e.g., X * Y)
  - use proper terminology from linear algebra (scalar, vector, matrix)!

<br>

**Some hints about the notation used in the images:**
- each circle **and** each line represent single numbers
- each vertically oriented set of circles represents an *n*-dimensional vector
- the **number of lines** *n* that come out of circle **on the right** represent an *n*-dimesional vector
- **assume multiplication** between circles and lines
- **Σ** means *summation of inputs* to that circle


9.

<img src="https://github.com/nalester/LING_5410/blob/main/Fig_1.png?raw=true">



output=x*y

10.

<img src="https://github.com/nalester/LING_5410/blob/main/Fig_2.png?raw=true">



output=x*y
elementwise multiplication

11.

<img src="https://github.com/nalester/LING_5410/blob/main/Fig_5.png?raw=true">


x.y
dot product

12.

<img src="https://github.com/nalester/LING_5410/blob/main/Fig_4.png?raw=true">



Matrix multiplication

## Write functions to solve the **AND**, **OR**, and **XOR** problems ($\star\star\star$)


---

We revisit the logical problems of AND, OR, and XOR discussed in class. 

- Your task is to **define one function for each relationship** using the solutions we covered in class.

- **Each function should take two arguments** `x1` and `x2` and return the appropriate truth value of 0 or 1.
  - If you need a refresher on defining functions in Python, [here](https://www.w3schools.com/python/python_functions.asp) is a straightforward tutorial.

- Do this using only tensors and the linear algebra we have learned in class! **No fancy `torch` solutions or otherwise!** Just the basics.
  - It doesn't need to be elegant, so long as it gets the job done.

- Demonstrate that your functions generate the expected output for all combinations of `x1` and `x2`.

**Hint**: You can ignore the second bias in XOR (it's value will always be 0)


13. **AND**

<center><img src="https://github.com/nalester/LING_5410/blob/main/Fig_and.png?raw=true"></center>


In [ ]:
def and_function(x1,x2):
  

14. **OR**

<center><img src="https://github.com/nalester/LING_5410/blob/main/Fig_or.png?raw=true"></center>

15. **XOR**

<center><img src="https://github.com/nalester/LING_5410/blob/main/Fig_XOR.png?raw=true"></center>